### ISSUE TITLE
Git folder structure

### ISSUE THREAD

**Issue by georgev93** [emailing-files-is-still-better/Ir-Blinky#11]
I would submit this in a PR, but this could get really nasty in a merge...

You could probably take your whole `LM IR BLinker.X` folder and move its contents into the root of this repo. The only thing to pay attention to is getting git to realize that the files have moved, rather than deleted and new files have been created elsewhere. I'm sure there's a great GUI way to do this, but in the terminal I was able to make this happen by doing the following:

1. Close out of MPLAB X
2. (Optional) `git clean -fdx` to get rid of any non-tracked files, garbage, and most importantly empty directories
3. `git mv LM\ IR\ BLinker.X/* .` when I was in the project root
  a. Notice that I didn't use `mv`, I used `git mv`. That's sometimes the difference of having git realize whats going on vs. having it think that old files are being deleted and new files are being created.
4. `rm -r LM\ IR\ BLinker.X`

Ensuring git realizes the files are just moving is important for git tracking the history of each individual file. If it thinks its a brand new file, then the history of that file will be split into two different places

**Comment by georgev93** [comment]
Also, did you notice that git functions are built into MPLAB X?! You can add/commit/push/pull/stash/etc. from within the IDE. I also really like that it does the blue/red/green highlighting of code changes, then you can click on those markers to see/revert to old code. Who knows, you might not even need the Github desktop GUI

**Comment by emailing-files-is-still-better** [comment]
I did not realize that but that is pretty cool. what would be the point of moving the project to the root?

**Comment by emailing-files-is-still-better** [comment]
I also saw the commit button in mplab but to be honest I just kinda figured out how github desktop works so I just rolled with that.

**Comment by georgev93** [comment]
Here's what you got:

![repo_before](https://user-images.githubusercontent.com/39860568/209920089-0f5f7cf6-b139-4fba-8581-11ca4041ca14.png)

Does not spark joy. What am I looking at? What does this repo contain? A folder and a .gitignore? I'm confused. What was changed when?

Here's what you could have:

![new_repo](https://user-images.githubusercontent.com/39860568/209920155-890caa4c-1d1a-4c02-bde3-c71fda1fee2c.png)

Oh wow, this is a repo that contains these sorts of files and folders. I can see when things were changed and what the changes were about right on the homepage!

**Comment by emailing-files-is-still-better** [comment]
Annnd He's back! I honestly forgot we talked about doing this. For whatever reason though, powershell doesn't like me trying to get into the .x directory. 

![image](https://user-images.githubusercontent.com/120235689/209931346-6c8c112b-c236-4005-a222-5efdad05eba8.png)

If I try to run git mv from the ir-blinky folder it give me an error saying source = destination.....

**Comment by georgev93** [comment]
That's "spaces in folder/file names" biting you. You'd need to capture the full path in quotes or use an escape character (maybe ^ in powershell?) before each space

**Comment by emailing-files-is-still-better** [comment]
![image](https://user-images.githubusercontent.com/120235689/209965036-8d057977-3c91-475c-bdd5-f2a8e35c9c70.png)
Quotes got me into the root folder, but still doesn't like something about the source.

**Comment by georgev93** [comment]
Fucking powershell... Why does it have to be SOOO different than shell/bash!?!? Ima google more about how you recursively `git mv` in powershell, but in the meantime you should have a `bash` installed on your computer if git was installed. It is a program called "git bash" and it should live at `C:\Program Files\Git\git-bash.exe`. If you run that you get a bash terminal and you can live it up in all of its Linux-y goodness. Then my commands should work.

Note: I did edit my original comment. The command is `git mv LM\ IR\ BLinker.X/* .` not `git mv LM\ IR\ BLinker.X\* .`. Not that that makes a difference in stupid powershell

**Comment by georgev93** [comment]
Eh. It looks like I was paranoid about nothing. You don't need to `git mv`. Instead you should just be able to move the files around like you want, then in the commit it should automatically figure out that things were renamed/moved, not deleted/created from scratch.

**Comment by emailing-files-is-still-better** [comment]
I moved them, and was too scared to push the commit button with 42 new files haha. But of the hub is smart enough I can try that later. Figured it was a PowerShell fighting me haha.

**Comment by georgev93** [comment]
Well that's the beauty of version control! There's no need to fear, since nothing is ever really gone! Well, you can rewrite history, but outside of that, everything is recoverable. Make a bad commit? Just undo it.

This is a super nitpicky issue, so don't take this thread to mean "he really wants me to do this" but rather take it as "he's taking a mental break from some literal shit by explaining programming/git stuff." No pressure to actually make this change.

## Undoing a Bad Commit

So what happens if you fuck this up? What happens if you make a bad commit you want to fix? Well first you need to remove that commit from your local workspace (on your computer, not on Github). You can do this by a "hard reset" back to a previous commit. You can refer to one commit back as "HEAD\~1", or two commits back as "HEAD\~2", etc. Here's an example of what hard reset does:

![](https://res.cloudinary.com/practicaldev/image/fetch/s--GqjwnYkF--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/hlh0kowt3hov1xhcku38.gif)

Boom. Just that easy. Bad commit is gone. Now what if you pushed that local workspace up to Github and you want to fix what's on Github? If you try to push your local workspace to this repo, you'll get a message letting you know that Github is already up to date, and has even more commits than you have! Well duh, Github, I want you to forget that! So you can add the "force" option to your push to force your exact history to the repo (`git push --force`), removing anything that Github has extra that you don't.

## Undoing a Bad Commit but it's not the Most Recent

So what if you make this change and you're okay with it now, but a few commits down the line you wish you hadn't done this? No worries, you can rearrange stuff pretty easily with an "interactive rebase". Just tell the rebase how far back in time you want to look, then it will open up a text editor where you can say what you want to do with the various commits in this section of history. It looks like this:

![](https://res.cloudinary.com/practicaldev/image/fetch/s--P6jr7igd--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/msofpv7k6rcmpaaefscm.gif)

Fix your local repo, then give the 'ol force push.

## Doing Things Outside Your Main Branch

But what if you want to test out your change before you screw up the main branch? Why not push to a branch called gitStructureChange or something like that. That process would look like this:

  - Create a branch
    - `git branch gitStructureChange`
  - Switch to that branch (you might need to stash any changes before you can switch)
    - `git checkout gitStructureChange`
  - Make your changes. Hell, make a few commits. This is where you can play with "experimental" changes and not worry about screwing up your main at all.
  - If you want to push your branch up to Github (maybe you want to see how it looks), you can push. However, you'll need to git what branch you're pushing to upstream (in fact, that upstream branch doesn't even exist yet). Your default "remote" repo that you're pushing to is named "origin" by default, so the CLI for pushing to the upstream branch "gitStructureChange" would be `git push --set-upstream origin gitStructureChange`.
    - You don't *need* to push your branch up to Github to merge it into your main. You can also do that within your local repo. Just checkout your main (`git checkout main`) and merge your new branch in (`git merge gitStructureChange`).
  - If you want to merge the branch into main in Github, just navigate to your newly pushed branch and follow the instructions to merge with main if you like how it looks. If you don't, just delete it! You can also delete your local branch (`git branch --delete gitStructureChange`). Once you've merged, you'll need your local main branch to be up to date with Github's main branch. So make sure you're in your main branch in your local repo (`git checkout main`) and pull (`git pull`). Again, once you're done with your local branch, you're welcome to delete it (`git branch --delete gitStructureChange`)

Branches and merging. It's the Git way!

Obviously I know you would like to do most of this through the GUI, but I've included the CLI options in case you can't find a button somewhere. Also, check out how simple those CLI commands are! Not very scary stuff.

## Cool Gifs Highlight

Super cool gifs, right? The second guy coming out to fill in for me turned me onto [this page](https://dev.to/lydiahallie/cs-visualized-useful-git-commands-37p1#reflog) which is very very cool. It's definitely worth scrolling the next time you're bored to demystify some of the fanciness of git.

**Comment by emailing-files-is-still-better** [comment]
That is all very informative, but what was the change that could have possibly been made? Didn't see that or at minimum, didn't understand what it was haha. We'll see if I feel confident enough to branch my own main one of these days...

**Comment by georgev93** [comment]
The change that this thread is about? Moving the files in your .X folder into the project root. My most recent comment was asserting that you need not be afraid of such a change because you could a) undo commits if something goes wrong or b) do things in a separate branch so if something goes wrong you don't need to undo anything (just delete the new branch)

**Comment by emailing-files-is-still-better** [comment]
Gotcha. That all makes sense. Knowing something is possible, and doing it though are distinctly different things. Luckily it all went as expected so I can delay that experience further.

**Comment by emailing-files-is-still-better** [comment]
Gotcha. That all makes sense. Knowing something is possible, and doing it though are distinctly different things. Luckily it all went as expected so I can delay that experience further.
