### ISSUE TITLE
MPLAB X Build Issues

### ISSUE THREAD

**Issue by georgev93** [emailing-files-is-still-better/Ir-Blinky#16]
![image](https://user-images.githubusercontent.com/120235689/230729578-2fca211b-01b0-48c5-bd7a-bbad10ffed9e.png)

So I have started to get this error, any ideas? I tried deleting the build file. This is also after discarding all changes I had made from working code. Also getting errors trying to change the bit length timer to 130us. the code is spitting out the binary values but at 38khz, not for the duration of the timer. each bit is 13us and I can't get that to change. Good news is LED is received by an arduino IR receiver so all good there. Now just need to get it spitting out the right code!

_Originally posted by @emailing-files-is-still-better in https://github.com/emailing-files-is-still-better/Ir-Blinky/issues/6#issuecomment-1500915500_

**Comment by georgev93** [comment]
Ooof, lost the picture

**Comment by emailing-files-is-still-better** [comment]
![image](https://user-images.githubusercontent.com/120235689/230751689-15d64f70-b95b-4673-b85d-9ef4dad2d059.png)

**Comment by georgev93** [comment]
I can't seem to recreate the issue, but that error seems to be related to the build files that Mplab X creates. Not sure how that got mangled. Likely some files are left behind from an old build, so Mplab X doesn't think it needs to regenerate those build files. I'd recommend manually cleaning the junk out from your folder. There are 3 ways I can think of to clean up:

## Use git's tool to delete any untracked files (GUI style)

Git has a tool called "clean". Somewhere in your GUI I'm sure there's a clean option. Clean is a function that removes any files that git doesn't track (i.e. the build files). If you use clean you'll need three extra options to get everything:

1. "Force" to force git to actually delete files
2. "Directories" to recursively go down through directories
3. "Don't use standard ignore rules" to specify you want to remove files you would typically ignore (the build files)

## Use git's tool to delete any untracked files (CLI style)

If you can pull up a command line that has git in the path, you can do this via this one liner:

`git clean -fdx`

## Manually delete files

Delete the build directory, dist directory, and everything in nbproject besides configurations.xml and project.xml

**Comment by emailing-files-is-still-better** [comment]
You are an expert my friend. Opened command line from my github desktop and ran your one liner. building correctly now!

**Comment by georgev93** [comment]
Gotta love that git CLI!
