### ISSUE TITLE
Disconnect PICKIT4

### ISSUE THREAD

**Issue by emailing-files-is-still-better** [emailing-files-is-still-better/Ir-Blinky#17]
How do I disconnect the PICKIT. I think that might be an issue with where I start to get some of these errors. It all seems to work when going from blue to orange status lights but then I can't get it back to blue. And then errors start popping up when I try to run or download.

**Comment by georgev93** [comment]
Sometimes I just have to pull out the USB cable to the Pickit if it gets in a nasty state.  Not something I typically have to do, but it does happen sometimes

**Comment by emailing-files-is-still-better** [comment]
So should i be using run? or make and program device. I am basically having to shut down mplab and unplug the pickit to get consistent downloads. Or at least to know for sure I am not pulling my hair out chasing something.

**Comment by georgev93** [comment]
![MPLAB_buttons](https://user-images.githubusercontent.com/39860568/230766091-3eccd898-db0f-4913-b06a-ca493a28530f.png)

From left to right our options are:

 - Build: Compile code without removing the old compiled code pieces. It should keep what it can and only build the new stuff
 - Clean and build: Delete all code that has already been compiled and compile again starting fresh.
 - Run: Not going to lie, not super familiar with this button...
 - Download: Build code if you haven't already (it should detect if you've made any changes which would justify a recompile), then download it to your microcontroller. The microcontroller will start running right away.
 - Upload: Read the code that's on the microcontroller (useful for storing images/reverse engineering)
 - Hold in Reset: If this icon has a pink pause button, you can click this button which will hold the microcontroller in a paused state. Then it changes from a pause icon to a play icon and you can click it again to release the microcontroller from its paused state. Not a very useful button most of the time.
 - Debug: This does the same thing that the download button does, but it also starts a debug session in the IDE that lets you use breakpoints, lets you step through code, and lets you observe registers and variables as the code is running. A debug session gives you another set of buttons like play, pause, step over, step into, and stop. You can stop a debug session by clicking stop.

So, when I'm just programming the microcontroller, I make my changes to the source code, then click the "download" button. If instead I care to see what is happening on the microcontroller, I click the "debug" button to watch it go, do my troubleshooting, then when I'm all done I click "stop" to stop the debugging session and click the "download" button to flash my normal code on the microcontroller. You might be able to get away with not "downloading" after your debug session, but different IDEs do different things, and some have a special "debug" version of the code that gets downloaded when you enter debug mode. Therefore, I always finish with a "download" to make sure I have the final deployable flash on the microcontroller.

**Comment by emailing-files-is-still-better** [comment]
Interesting. I was getting into a weird loop where I would download and get the code running, but when hitting download again with the pickit already powering the board it would freeze up and then start giving errors. Could be I need to update mplab too since it keeps telling at me to do that.

**Comment by georgev93** [comment]
In college I remember I lent out my Pickit 3 to a buddy (as one does), but when I got it back it had lots of issues. It turned out my buddy had a newer version of Mplab X, which updated the firmware of the pickit to a newer version, which made it incompatible with my software. Maybe this is a similar thing

**Comment by emailing-files-is-still-better** [comment]
I did just update a pack related to pickit 4 so maybe that will help.

**Comment by emailing-files-is-still-better** [comment]
Updating the pic16F pack made a huge difference, seems to be working as it should now.
