### ISSUE TITLE
Bit precision: full square waves

### ISSUE THREAD

**Issue by georgev93** [emailing-files-is-still-better/Ir-Blinky#2]
Right now the bits are only done in complete periods. Since our modulation period is ~13.4us, that could result in us getting pretty far off in timing over the whole packet. The "pulse" function should not only be able to pulse in complete periods, but also fractional periods

**Comment by emailing-files-is-still-better** [comment]
yep, that is why this library looked promising. 

https://github.com/khoih-prog/AVR_PWM/blob/main/examples/PWM_Basic/PWM_Basic.ino

I thought this would work and be able to generate frequencies, then just use a 50% duty cycle for 1's and a 0% duty cycle for 0's and using delay to pulse out the bits. But I could not get this thing to output anything on my LED.

**Comment by emailing-files-is-still-better** [comment]
Tried running just that basic file as is and with changes I think would make sense and there is literally nothing coming off  of pin 10 according to shirmp and the data led on my ir transmit module

**Comment by georgev93** [comment]
Hmm. At a glance I don't know why that wouldn't work out of the box, but even if it did it wouldn't port to pic very well

**Comment by emailing-files-is-still-better** [comment]
Also, I think arduino is introducing some weird timing delays, becuase in the pulse function now I have to divide those values by 3 ish to get the right timing on the shrimp. and that is reading right off of the nano pin. unless i have the shrimp configured wrong and it is amplifying time?

**Comment by georgev93** [comment]
https://github.com/emailing-files-is-still-better/Ir-Blinky/issues/3#issuecomment-1345233738

**Comment by georgev93** [comment]
https://github.com/emailing-files-is-still-better/Ir-Blinky/issues/6#issuecomment-1500915500

> getting errors trying to change the bit length timer to 130us. the code is spitting out the binary values but at 38khz, not for the duration of the timer. each bit is 13us and I can't get that to change.

So you're saying you're changing the TMR0 period and it doesn't seem to change the bit length? Based on your current commit it looks like the TMR0 period is set to 32.5us. When I had the board on my Oscope I was seeing roughly 28us (although it's hard to tell with the modulated signal, so +/- 6.5us).

Just to be clear, we're talking about the bit time (time during the output is a square wave or flat) is 13us? Rather than the modulation showing high periods of 13us, which would be by design if a full period of the modulation is 26us

**Comment by emailing-files-is-still-better** [comment]
Correct, when changing from 32.5 to 128 the time the pwm pulse is on for does not seem to change. This was also at my quitting time last night so I should run it a few more times to verify before spinning you up on a rabbit hole.

**Comment by georgev93** [comment]
Rgr. Well when you do double check that, make sure your seeing changes in the following place before you recompile:

mcc_generated_files/tmr0.c: line 69 (setting `TMR0H`)

There might also be changes on line 72 as well (setting `TMR0L`). These registers determine the period of your timer.

I haven't messed with MCC too much, but the times I have I get annoyed at having to click the "generate code" button after making a change in the GUI to actually push my changes to the source code

**Comment by emailing-files-is-still-better** [comment]
yeah I was making sure to generate, as I had that happen when changing from 6.5 to 26 on the other timer. But it is good to know the changes I should be seeing.

**Comment by emailing-files-is-still-better** [comment]
![image](https://user-images.githubusercontent.com/120235689/230756978-331d0bb7-4596-4bb0-854a-0ef113012134.png)

This is the first section of the preamble with the TMR0 set to 128us. It is unchanged from when the timer was set to 32.5us, both around 90us. I verified in the hub desktop that the file has changed can see that the value was changed as shown below:

         <value>0.0000325</value>
         <value>0.000128</value>

**Comment by georgev93** [comment]
Well sure enough you should be changing the TMR0 period based on your latest commit. It's very weird because the simulator agrees that changing the TMR0 period should change the bit rate. A few things to check to make sure your code changes are getting to your microcontroller:

1. Try clean&build between downloads
2. Try commenting out line 63 of main.c where we change PWM_EN. This should stop transmitting bits all together. This should help us verify that your code changes are actually making it to the chip

**Comment by emailing-files-is-still-better** [comment]
![image](https://user-images.githubusercontent.com/120235689/230758497-4aa080ff-fdb6-43bc-b024-e85bab9385a6.png)
Not gonna lie MPLAB is starting to get old haha. Literally was running it getting one thing. Closed it, did the one line clean, then opened it up with no changes and ran build/clean and download and got the above. Gonna give me more grey hairs. looks like its up to 122us so I will change the post scaler to try to get closer to the 135-140 I am seeing on the shrimp.

**Comment by georgev93** [comment]
Yeah, I'm not a fan of Mplab X. It looks like garbage and has some nasty bugs. I wonder if at some point it stop talking to the PK4 and switched to simulator instead?

**Comment by emailing-files-is-still-better** [comment]
I think this issue is solved, output is reading pretty close to what the commanded bit length is.
