### ISSUE TITLE
Pulses from shrimp not matching the first ten to the second ten

### ISSUE THREAD

**Issue by emailing-files-is-still-better** [emailing-files-is-still-better/Ir-Blinky#28]
![image](https://user-images.githubusercontent.com/120235689/233512549-490fa20d-06cf-45d5-9979-0685d98541c7.png)
Occasionally I get pulses that look like this. Discussion ensue...

**Comment by georgev93** [comment]
Fixed by ed082bb39a3ec57b4ae8585417a24bbd29224336
