### ISSUE TITLE
Modulation precision

### ISSUE THREAD

**Issue by georgev93** [emailing-files-is-still-better/Ir-Blinky#3]
The only way we can adjust the modulation given the current scheme is in 2us steps (1us changes to the delay between each bit transition). For instance, if we were at 37kHz and we wanted to be slower, our only option would be to slow down the pulse routine by 2us, which would result in 34.5kHz. That's not a lot of fidelity.

**Comment by georgev93** [comment]
Also, could you verify that it actually outputs the right modulation frequency with the shrimp? Just probe the Arduino output pin

**Comment by emailing-files-is-still-better** [comment]
Each high and low is 41us with your file. But math looks just fine at least. pulse(422) was 370us long. DelayMicroseconds(130/3.258) was 179us. So also a bit off, for some reason.

![LM 76 output sample 1](https://user-images.githubusercontent.com/120235689/206841498-5db7020c-73de-43e3-ad83-4ed55af09cd3.png)

**Comment by emailing-files-is-still-better** [comment]
![LM 76 output sample 2](https://user-images.githubusercontent.com/120235689/206841543-02cd0a57-35b2-4d9f-8455-5a7932033dbc.png)

**Comment by georgev93** [comment]
Wow. Look at those screenshots! What a great platform for a technical discussion Github is!

I found a pretty slick online simulator so I can play along. [Here](https://wokwi.com/projects/350651309737640530)'s the code with a serial output to verify our delay times. Looks like it agrees that the period of a complete pulse is 80us (close to your 82us measurement). But for `delayMicroseconds(130/3.258);` it is showing 40us.

**Comment by georgev93** [comment]
Looking at the output of the simulated logic analyzer, it is showing 13us highs and lows for pulse... who do we trust... Can you right some code to blink a physical LED at a rate like 1Hz, then verify it with your watch? When we know the arduino is working correctly, you could connect the shrimp and make sure you measure 1Hz, then we'd know the shrimp is working correctly

**Comment by georgev93** [comment]
Also, if we eventually feel like not chasing our tails anymore, the correct answer for precise timing (for our modulation, and our bit width) is using a timer and not relying on silly functions like delayMicroseconds which count on instructions taking a certain number of clock cycles to complete. But there is almost no overlap between timers on Arduino vs. timers on pic, so it would all be wasted effort when the boards come in

**Comment by emailing-files-is-still-better** [comment]
Yeah I think there's a default program to blink the on board led so that should be pretty simple.

**Comment by emailing-files-is-still-better** [comment]
I also feel like on my end tail chasing has already been achieved haha. I've also no clue how to implement the timers.

**Comment by georgev93** [comment]
I have never done a timer on arduino, but there are a bunch of how-tos out there. However, you'd need to learn pic times to program the custom board. So if it were me, I'd take a pause, wait for the PCBs to come in, then program the pics

**Comment by emailing-files-is-still-better** [comment]
I also feel like on my end tail chasing has already been achieved haha. I've also no clue how to implement the timers. Agreed, that makes sense. I thought Arduino would be a good in between, but mostly just running in circles lol

**Comment by georgev93** [comment]
Well also keep in mind that when it comes to programming the pic, you won't need to set up anything with the timers in code. Rather, there's a gui to configure the timers. I'd argue that pic development is simpler than arduino development. The only advantage arduino has is that so many people already have code libraries written and available

**Comment by emailing-files-is-still-better** [comment]
Well that's confidence inspiring. I would have thought this would be super
simple on Arduino haha

**Comment by emailing-files-is-still-better** [comment]
So everything is not working properly, or so it seems. Using stock arduino blink program, for 1 second on, one second off, it takes 4 seconds to complete each cycle. even sampling at 10 hz I can't get shrimp to pick it up. I changed arduino to 50ms blinks which is something like 4 times slower than that and shrimp gives me this:

![image](https://user-images.githubusercontent.com/120235689/207349294-7465ae3b-67fd-4c7c-88b9-0910ff82ea65.png)

I am not even sure how to interpret this since the scale is so out of whack lol. Any musings?

**Comment by emailing-files-is-still-better** [comment]
![image](https://user-images.githubusercontent.com/120235689/208066702-6bea735d-27c7-4e11-aea6-99e59c6bae28.png)

Seems like a valuable tool.  So I have 38khz even though my wizard is telling me that it is 77khz, but i think the period calculation is off on that. Now just need to get that pin toggling 38k and use your interrupt to generate each discrete pulse.

**Comment by emailing-files-is-still-better** [comment]
![Uploading image.png…]()

duty cycle of 0 turns the pin off

**Comment by georgev93** [comment]
That's weird about the double period length... I tried changing the duty cycle to 10%, and sure enough, it stays a 26us period.

I also see this error:

![Screenshot from 2022-12-16 17-45-37](https://user-images.githubusercontent.com/39860568/208081698-da6d18e3-9b7d-480b-b0b3-e1223a4e4672.png)

I hope that's not screwing things up

**Comment by emailing-files-is-still-better** [comment]
![image](https://user-images.githubusercontent.com/120235689/208224258-685bc9d6-db6a-4ff6-b05f-b84bc83b178f.png)
So just doing a 50% duty 38k square wave looks good. but when adding the zero duty and some delays things get weird, and I haven't been able to figure out why lol 
![image](https://user-images.githubusercontent.com/120235689/208224335-696917a2-540a-4ee2-a7c3-25405587ab3b.png)
I was trying to use a timer to pulse on and off at some delay but haven't gotten there yet in my unlearned state.

**Comment by georgev93** [comment]
Hmm... well we should definitely stay away from "delay" functions for precise timing. That might be some of the funkiness. PR #8 is probably a better way to go about this

**Comment by emailing-files-is-still-better** [comment]
![image](https://user-images.githubusercontent.com/120235689/208251067-bafe79aa-8d78-4eb5-8af0-19e0e1affbdb.png)
LA output from the last if statement commit. looks like 5 blips of instruction cycle time for each of the back to back zero's. Though shouldn't matter to a 38khz receiver yeah?

**Comment by emailing-files-is-still-better** [comment]
Actually, maybe if I initialized the pwm at 0% duty the blip would go away? Can test that tomorrow.

**Comment by georgev93** [comment]
Looks like your guess that the simulator was wrong in commit 56a299be25b547027ec6a959506f5ee462007bde was correct. I verified that the hardware is actually spitting out 154kHz, which is good news because that is what MCC thinks that TMR2 should be spitting out (it is set to a 6.5us output). The MPLAB X simulator still thinks the frequency output should be 38.4kHz. Just off by a factor of 4 I guess...

The measured  bit times also correspond to be about 4 times faster than the simulator predicts, so good news there. If you set the simulator to show time as Instruction Cycles rather than microseconds, it ends up being accurate. However, it thinks 1 instruction cycle is 1us in the current configuration. 1 instruction cycle is 4 ticks of the clock, so if our clock is ticking at 16MHz, an instruction cycle actually takes 0.25us
