### ISSUE TITLE
Which timer for what

### ISSUE THREAD

**Issue by georgev93** [emailing-files-is-still-better/Ir-Blinky#9]
So my MCC does show TMR0, TMR1, and TMR2 for the PIC16F15214

![Screenshot from 2022-12-17 15-42-37](https://user-images.githubusercontent.com/39860568/208233744-8f1018ca-4a94-4272-babc-9e62085772d3.png)

Is that not showing up for you?

**Comment by emailing-files-is-still-better** [comment]
Yeah it is there.....now.... haha. Not sure why I thought I didn't see it before.
